### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by sfmth** [ATofighi/skyroom-record#5]
SUT has successfully closed Aparat channels that distributed recorded classes. You might want to add personal use only description to the readme.md file and disclaim any abuse made by this code as you might be susceptible to DCMA takedowns.

**Comment by ATofighi** [comment]
Oppps!  @sfmth Can you create a PR for that please?

**Comment by sfmth** [comment]
You can use a cc license as it includes a disclaimer: https://creativecommons.org/choose/
This work is licensed under a Creative Commons Attribution 4.0 International License, 
The project is offered “as-is”, without warranty, and we disclaim liability for damages resulting from using or abusing the project.
